add_test( [==[Geometry Test case]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Geometry Test case]==]  )
set_tests_properties( [==[Geometry Test case]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Sphere Methods]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Sphere Methods]==]  )
set_tests_properties( [==[Sphere Methods]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[AABB Methods]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[AABB Methods]==]  )
set_tests_properties( [==[AABB Methods]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Sphere Intersections]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Sphere Intersections]==]  )
set_tests_properties( [==[Sphere Intersections]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Plane Intersections]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Plane Intersections]==]  )
set_tests_properties( [==[Plane Intersections]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Aabb Sphere Intersections]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Aabb Sphere Intersections]==]  )
set_tests_properties( [==[Aabb Sphere Intersections]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Sphere AABB Intersection (troubleshooting bug)]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Sphere AABB Intersection (troubleshooting bug)]==]  )
set_tests_properties( [==[Sphere AABB Intersection (troubleshooting bug)]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Aabb Aabb Intersections]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Aabb Aabb Intersections]==]  )
set_tests_properties( [==[Aabb Aabb Intersections]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Ray Aabb Intersections]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Ray Aabb Intersections]==]  )
set_tests_properties( [==[Ray Aabb Intersections]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Sphere Contacts]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Sphere Contacts]==]  )
set_tests_properties( [==[Sphere Contacts]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Aabb Aabb Contacts]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Aabb Aabb Contacts]==]  )
set_tests_properties( [==[Aabb Aabb Contacts]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Hierarchy and frustum branches]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Hierarchy and frustum branches]==]  )
set_tests_properties( [==[Hierarchy and frustum branches]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Heightmap collisions and unsupported pair branches]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Heightmap collisions and unsupported pair branches]==]  )
set_tests_properties( [==[Heightmap collisions and unsupported pair branches]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
add_test( [==[Contact utility branches]==] /tmp/workspace/leandrolillo/geometry/build_cov/test/geometry_unit_tests [==[Contact utility branches]==]  )
set_tests_properties( [==[Contact utility branches]==] PROPERTIES WORKING_DIRECTORY /tmp/workspace/leandrolillo/geometry/build_cov/test)
set( geometry_unit_tests_TESTS [==[Geometry Test case]==] [==[Sphere Methods]==] [==[AABB Methods]==] [==[Sphere Intersections]==] [==[Plane Intersections]==] [==[Aabb Sphere Intersections]==] [==[Sphere AABB Intersection (troubleshooting bug)]==] [==[Aabb Aabb Intersections]==] [==[Ray Aabb Intersections]==] [==[Sphere Contacts]==] [==[Aabb Aabb Contacts]==] [==[Hierarchy and frustum branches]==] [==[Heightmap collisions and unsupported pair branches]==] [==[Contact utility branches]==])
